/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bicycle_model_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {34, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {7, 1, 1};

/* bicycle_model_cost_ext_cost_fun_jac:(i0[5],i1[2],i2[0],i3[34])->(o0,o1[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=1.0000000000000001e-01;
  a01=arg[0]? arg[0][0] : 0;
  a02=arg[3]? arg[3][0] : 0;
  a02=(a01-a02);
  a03=(a00*a02);
  a02=(a03*a02);
  a04=arg[0]? arg[0][1] : 0;
  a05=arg[3]? arg[3][1] : 0;
  a05=(a04-a05);
  a06=(a00*a05);
  a05=(a06*a05);
  a02=(a02+a05);
  a05=2.0000000000000001e-01;
  a07=arg[0]? arg[0][2] : 0;
  a08=arg[3]? arg[3][2] : 0;
  a07=(a07-a08);
  a05=(a05*a07);
  a07=(a05*a07);
  a02=(a02+a07);
  a07=arg[0]? arg[0][3] : 0;
  a08=arg[3]? arg[3][3] : 0;
  a07=(a07-a08);
  a08=(a00*a07);
  a07=(a08*a07);
  a02=(a02+a07);
  a07=5.0000000000000003e-02;
  a09=arg[1]? arg[1][0] : 0;
  a07=(a07*a09);
  a10=(a07*a09);
  a11=arg[1]? arg[1][1] : 0;
  a12=(a00*a11);
  a13=(a12*a11);
  a10=(a10+a13);
  a02=(a02+a10);
  a10=4.0000000000000002e-01;
  a13=arg[3]? arg[3][5] : 0;
  a09=(a09-a13);
  a10=(a10*a09);
  a09=(a10*a09);
  a13=arg[3]? arg[3][6] : 0;
  a11=(a11-a13);
  a00=(a00*a11);
  a11=(a00*a11);
  a09=(a09+a11);
  a02=(a02+a09);
  a09=10.;
  a11=arg[0]? arg[0][4] : 0;
  a13=casadi_sq(a11);
  a13=(a09*a13);
  a02=(a02+a13);
  a13=50.;
  a14=arg[3]? arg[3][10] : 0;
  a15=arg[3]? arg[3][11] : 0;
  a14=(a14+a15);
  a15=2.;
  a14=(a14/a15);
  a16=1.;
  a14=(a14+a16);
  a17=casadi_sq(a14);
  a18=(a13*a17);
  a19=arg[3]? arg[3][7] : 0;
  a19=(a01-a19);
  a20=casadi_sq(a19);
  a21=arg[3]? arg[3][8] : 0;
  a21=(a04-a21);
  a22=casadi_sq(a21);
  a20=(a20+a22);
  a22=casadi_fmax(a20,a17);
  a18=(a18/a22);
  a14=(a09*a14);
  a14=casadi_sq(a14);
  a14=(a14<a20);
  a14=(a16-a14);
  a23=(a18*a14);
  a24=arg[3]? arg[3][15] : 0;
  a25=arg[3]? arg[3][16] : 0;
  a24=(a24+a25);
  a24=(a24/a15);
  a24=(a24+a16);
  a25=casadi_sq(a24);
  a26=(a13*a25);
  a27=arg[3]? arg[3][12] : 0;
  a27=(a01-a27);
  a28=casadi_sq(a27);
  a29=arg[3]? arg[3][13] : 0;
  a29=(a04-a29);
  a30=casadi_sq(a29);
  a28=(a28+a30);
  a30=casadi_fmax(a28,a25);
  a26=(a26/a30);
  a24=(a09*a24);
  a24=casadi_sq(a24);
  a24=(a24<a28);
  a24=(a16-a24);
  a31=(a26*a24);
  a23=(a23+a31);
  a31=arg[3]? arg[3][20] : 0;
  a32=arg[3]? arg[3][21] : 0;
  a31=(a31+a32);
  a31=(a31/a15);
  a31=(a31+a16);
  a15=casadi_sq(a31);
  a13=(a13*a15);
  a32=arg[3]? arg[3][17] : 0;
  a01=(a01-a32);
  a32=casadi_sq(a01);
  a33=arg[3]? arg[3][18] : 0;
  a04=(a04-a33);
  a33=casadi_sq(a04);
  a32=(a32+a33);
  a33=casadi_fmax(a32,a15);
  a13=(a13/a33);
  a31=(a09*a31);
  a31=casadi_sq(a31);
  a31=(a31<a32);
  a16=(a16-a31);
  a31=(a13*a16);
  a23=(a23+a31);
  a02=(a02+a23);
  if (res[0]!=0) res[0][0]=a02;
  a10=(a10+a10);
  a10=(a10+a07);
  a10=(a10+a07);
  if (res[1]!=0) res[1][0]=a10;
  a00=(a00+a00);
  a00=(a00+a12);
  a00=(a00+a12);
  if (res[1]!=0) res[1][1]=a00;
  a03=(a03+a03);
  a01=(a01+a01);
  a00=(a15<=a32);
  a32=(a32<=a15);
  a32=(a00+a32);
  a00=(a00/a32);
  a13=(a13/a33);
  a13=(a13*a16);
  a00=(a00*a13);
  a01=(a01*a00);
  a27=(a27+a27);
  a13=(a25<=a28);
  a28=(a28<=a25);
  a28=(a13+a28);
  a13=(a13/a28);
  a26=(a26/a30);
  a26=(a26*a24);
  a13=(a13*a26);
  a27=(a27*a13);
  a01=(a01+a27);
  a19=(a19+a19);
  a27=(a17<=a20);
  a20=(a20<=a17);
  a20=(a27+a20);
  a27=(a27/a20);
  a18=(a18/a22);
  a18=(a18*a14);
  a27=(a27*a18);
  a19=(a19*a27);
  a01=(a01+a19);
  a03=(a03-a01);
  if (res[1]!=0) res[1][2]=a03;
  a06=(a06+a06);
  a04=(a04+a04);
  a04=(a04*a00);
  a29=(a29+a29);
  a29=(a29*a13);
  a04=(a04+a29);
  a21=(a21+a21);
  a21=(a21*a27);
  a04=(a04+a21);
  a06=(a06-a04);
  if (res[1]!=0) res[1][3]=a06;
  a05=(a05+a05);
  if (res[1]!=0) res[1][4]=a05;
  a08=(a08+a08);
  if (res[1]!=0) res[1][5]=a08;
  a11=(a11+a11);
  a09=(a09*a11);
  if (res[1]!=0) res[1][6]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real bicycle_model_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
