/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bicycle_model_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {34, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {7, 1, 1};
static const casadi_int casadi_s6[19] = 
  {7, 7, 0, 1, 2, 4, 6, 7,
  8, 9, 0, 1, 2, 3, 2, 3,
  4, 5, 6};
static const casadi_int casadi_s7[3] = {0, 0, 1};
static const casadi_int casadi_s8[3] = {0, 7, 1};

/* bicycle_model_cost_ext_cost_0_fun_jac_hess:(i0[5],i1[2],i2[0],i3[34])->(o0,o1[7],o2[7x7,9nz],o3[],o4[0x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36;
  a00=1.0000000000000001e-01;
  a01=arg[0]? arg[0][0] : 0;
  a02=arg[3]? arg[3][0] : 0;
  a02=(a01-a02);
  a03=(a00*a02);
  a02=(a03*a02);
  a04=arg[0]? arg[0][1] : 0;
  a05=arg[3]? arg[3][1] : 0;
  a05=(a04-a05);
  a06=(a00*a05);
  a05=(a06*a05);
  a02=(a02+a05);
  a05=2.0000000000000001e-01;
  a07=arg[0]? arg[0][2] : 0;
  a08=arg[3]? arg[3][2] : 0;
  a07=(a07-a08);
  a08=(a05*a07);
  a07=(a08*a07);
  a02=(a02+a07);
  a07=arg[0]? arg[0][3] : 0;
  a09=arg[3]? arg[3][3] : 0;
  a07=(a07-a09);
  a09=(a00*a07);
  a07=(a09*a07);
  a02=(a02+a07);
  a07=5.0000000000000003e-02;
  a10=arg[1]? arg[1][0] : 0;
  a07=(a07*a10);
  a11=(a07*a10);
  a12=arg[1]? arg[1][1] : 0;
  a13=(a00*a12);
  a14=(a13*a12);
  a11=(a11+a14);
  a02=(a02+a11);
  a11=4.0000000000000002e-01;
  a14=arg[3]? arg[3][5] : 0;
  a10=(a10-a14);
  a14=(a11*a10);
  a10=(a14*a10);
  a15=arg[3]? arg[3][6] : 0;
  a12=(a12-a15);
  a00=(a00*a12);
  a12=(a00*a12);
  a10=(a10+a12);
  a02=(a02+a10);
  a10=10.;
  a12=arg[0]? arg[0][4] : 0;
  a15=casadi_sq(a12);
  a15=(a10*a15);
  a02=(a02+a15);
  a15=50.;
  a16=arg[3]? arg[3][10] : 0;
  a17=arg[3]? arg[3][11] : 0;
  a16=(a16+a17);
  a17=2.;
  a16=(a16/a17);
  a18=1.;
  a16=(a16+a18);
  a19=casadi_sq(a16);
  a20=(a15*a19);
  a21=arg[3]? arg[3][7] : 0;
  a21=(a01-a21);
  a22=casadi_sq(a21);
  a23=arg[3]? arg[3][8] : 0;
  a23=(a04-a23);
  a24=casadi_sq(a23);
  a22=(a22+a24);
  a24=casadi_fmax(a22,a19);
  a20=(a20/a24);
  a16=(a10*a16);
  a16=casadi_sq(a16);
  a16=(a16<a22);
  a16=(a18-a16);
  a25=(a20*a16);
  a26=arg[3]? arg[3][15] : 0;
  a27=arg[3]? arg[3][16] : 0;
  a26=(a26+a27);
  a26=(a26/a17);
  a26=(a26+a18);
  a27=casadi_sq(a26);
  a28=(a15*a27);
  a29=arg[3]? arg[3][12] : 0;
  a29=(a01-a29);
  a30=casadi_sq(a29);
  a31=arg[3]? arg[3][13] : 0;
  a31=(a04-a31);
  a32=casadi_sq(a31);
  a30=(a30+a32);
  a32=casadi_fmax(a30,a27);
  a28=(a28/a32);
  a26=(a10*a26);
  a26=casadi_sq(a26);
  a26=(a26<a30);
  a26=(a18-a26);
  a33=(a28*a26);
  a25=(a25+a33);
  a33=arg[3]? arg[3][20] : 0;
  a34=arg[3]? arg[3][21] : 0;
  a33=(a33+a34);
  a33=(a33/a17);
  a33=(a33+a18);
  a34=casadi_sq(a33);
  a15=(a15*a34);
  a35=arg[3]? arg[3][17] : 0;
  a01=(a01-a35);
  a35=casadi_sq(a01);
  a36=arg[3]? arg[3][18] : 0;
  a04=(a04-a36);
  a36=casadi_sq(a04);
  a35=(a35+a36);
  a36=casadi_fmax(a35,a34);
  a15=(a15/a36);
  a33=(a10*a33);
  a33=casadi_sq(a33);
  a33=(a33<a35);
  a18=(a18-a33);
  a33=(a15*a18);
  a25=(a25+a33);
  a02=(a02+a25);
  if (res[0]!=0) res[0][0]=a02;
  a14=(a14+a14);
  a14=(a14+a07);
  a14=(a14+a07);
  if (res[1]!=0) res[1][0]=a14;
  a00=(a00+a00);
  a00=(a00+a13);
  a00=(a00+a13);
  if (res[1]!=0) res[1][1]=a00;
  a03=(a03+a03);
  a01=(a01+a01);
  a00=(a34<=a35);
  a35=(a35<=a34);
  a35=(a00+a35);
  a00=(a00/a35);
  a15=(a15/a36);
  a35=(a15*a18);
  a35=(a00*a35);
  a34=(a01*a35);
  a29=(a29+a29);
  a13=(a27<=a30);
  a30=(a30<=a27);
  a30=(a13+a30);
  a13=(a13/a30);
  a28=(a28/a32);
  a30=(a28*a26);
  a30=(a13*a30);
  a27=(a29*a30);
  a34=(a34+a27);
  a21=(a21+a21);
  a27=(a19<=a22);
  a22=(a22<=a19);
  a22=(a27+a22);
  a27=(a27/a22);
  a20=(a20/a24);
  a22=(a20*a16);
  a22=(a27*a22);
  a19=(a21*a22);
  a34=(a34+a19);
  a03=(a03-a34);
  if (res[1]!=0) res[1][2]=a03;
  a06=(a06+a06);
  a04=(a04+a04);
  a03=(a04*a35);
  a31=(a31+a31);
  a34=(a31*a30);
  a03=(a03+a34);
  a23=(a23+a23);
  a34=(a23*a22);
  a03=(a03+a34);
  a06=(a06-a03);
  if (res[1]!=0) res[1][3]=a06;
  a08=(a08+a08);
  if (res[1]!=0) res[1][4]=a08;
  a09=(a09+a09);
  if (res[1]!=0) res[1][5]=a09;
  a12=(a12+a12);
  a10=(a10*a12);
  if (res[1]!=0) res[1][6]=a10;
  a10=9.0000000000000013e-01;
  if (res[2]!=0) res[2][0]=a10;
  if (res[2]!=0) res[2][1]=a11;
  a35=(a17*a35);
  a10=(a00*a01);
  a12=(a15*a10);
  a12=(a12/a36);
  a09=(a15/a36);
  a10=(a09*a10);
  a12=(a12+a10);
  a12=(a18*a12);
  a12=(a00*a12);
  a12=(a01*a12);
  a12=(a35-a12);
  a30=(a17*a30);
  a10=(a13*a29);
  a08=(a28*a10);
  a08=(a08/a32);
  a06=(a28/a32);
  a10=(a06*a10);
  a08=(a08+a10);
  a08=(a26*a08);
  a08=(a13*a08);
  a08=(a29*a08);
  a08=(a30-a08);
  a12=(a12+a08);
  a17=(a17*a22);
  a22=(a27*a21);
  a08=(a20*a22);
  a08=(a08/a24);
  a10=(a20/a24);
  a22=(a10*a22);
  a08=(a08+a22);
  a08=(a16*a08);
  a08=(a27*a08);
  a08=(a21*a08);
  a08=(a17-a08);
  a12=(a12+a08);
  a12=(a05-a12);
  if (res[2]!=0) res[2][2]=a12;
  a12=(a00*a04);
  a15=(a15*a12);
  a15=(a15/a36);
  a09=(a09*a12);
  a15=(a15+a09);
  a18=(a18*a15);
  a00=(a00*a18);
  a01=(a01*a00);
  a18=(a13*a31);
  a28=(a28*a18);
  a28=(a28/a32);
  a06=(a06*a18);
  a28=(a28+a06);
  a26=(a26*a28);
  a13=(a13*a26);
  a29=(a29*a13);
  a01=(a01+a29);
  a29=(a27*a23);
  a20=(a20*a29);
  a20=(a20/a24);
  a10=(a10*a29);
  a20=(a20+a10);
  a16=(a16*a20);
  a27=(a27*a16);
  a21=(a21*a27);
  a01=(a01+a21);
  if (res[2]!=0) res[2][3]=a01;
  if (res[2]!=0) res[2][4]=a01;
  a04=(a04*a00);
  a35=(a35-a04);
  a31=(a31*a13);
  a30=(a30-a31);
  a35=(a35+a30);
  a23=(a23*a27);
  a17=(a17-a23);
  a35=(a35+a17);
  a35=(a05-a35);
  if (res[2]!=0) res[2][5]=a35;
  if (res[2]!=0) res[2][6]=a11;
  if (res[2]!=0) res[2][7]=a05;
  a05=20.;
  if (res[2]!=0) res[2][8]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real bicycle_model_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
