mission_mapping:
  # 장애물 탐지 미션 (장애물 회피 구간)
  obstacle:
    - start: 7    # 드럼통
      end: 7      
    - start: 19    # 사람
      end: 19
    
  # 라바콘 탐지 미션
  rubber:
    - start: 21   # 사선 주차
      end: 21

  # U-turn 미션
  rubber_uturn:
    - start: 25   # 유턴
      end: 25